PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE run_metrics (
	id INTEGER NOT NULL, 
	run_id INTEGER, 
	sub_run_id INTEGER, 
	run_name VARCHAR(100), 
	descrip VARCHAR(500), 
	config_id VARCHAR(6), 
	data_loader_type VARCHAR(20) NOT NULL, 
	dataset_name VARCHAR(100) NOT NULL, 
	embedder_type VARCHAR(20) NOT NULL, 
	embedder_model_name VARCHAR(100) NOT NULL, 
	embedder_parameters VARCHAR, 
	num_simulations INTEGER NOT NULL, 
	num_rounds INTEGER NOT NULL, 
	num_variants INTEGER NOT NULL, 
	num_variants_first_round INTEGER NOT NULL, 
	num_top_acq_var_per_round INTEGER NOT NULL, 
	num_top_pred_var_per_round INTEGER NOT NULL, 
	num_top_n_pred_per_round INTEGER, 
	batch_size INTEGER NOT NULL, 
	test_fraction FLOAT NOT NULL, 
	random_seed INTEGER NOT NULL, 
	max_assay_score FLOAT NOT NULL, 
	binary_score_cutoff FLOAT, 
	model_name VARCHAR(50) NOT NULL, 
	model_parameters VARCHAR, 
	first_round_strategy VARCHAR(100) NOT NULL, 
	first_round_strategy_params VARCHAR, 
	strategy VARCHAR(100) NOT NULL, 
	strategy_parameters VARCHAR, 
	start_ts DATETIME, 
	end_ts DATETIME, 
	end_round_num INTEGER, 
	mean_fha FLOAT, 
	mean_fha_rank INTEGER, 
	mean_activity FLOAT, 
	mean_activity_rank INTEGER, 
	max_activity FLOAT, 
	max_activity_rank INTEGER, 
	train_rmse FLOAT, 
	train_rmse_rank INTEGER, 
	train_r2 FLOAT, 
	train_r2_rank INTEGER, 
	train_spearm FLOAT, 
	train_spearm_rank INTEGER, 
	val_rmse FLOAT, 
	val_rmse_rank INTEGER, 
	val_r2 FLOAT, 
	val_r2_rank INTEGER, 
	val_spearm FLOAT, 
	val_spearm_rank INTEGER, 
	total_rank FLOAT, 
	PRIMARY KEY (id)
);
COMMIT;
