# config file for minerva, i.e. directories are different
db:
  url: "sqlite:///./../../data/al/db/msalde.db"
sub_runs:
  config_file: "./config/simulations.yaml"
general:
  store_acquired_variants: false
datasets:
  brenan:
    data_loader_type: file_loader
    input_path: "/sc/arion/work/fratac01/data/al/dms/brenan_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/brenan_esm2_t33_650M_UR50D.csv
  jones:
    data_loader_type: file_loader
    input_path: "/sc/arion/work/fratac01/data/al/dms/jones_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/jones_esm2_t33_650M_UR50D.csv
  cas12f:
    data_loader_type: file_loader
    input_path: "/sc/arion/work/fratac01/data/al/dms/cas12f_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/cas12f_esm2_t33_650M_UR50D.csv
  cas12f1:
    data_loader_type: file_loader
    input_path: "../EvolvePro/output/dms/cas12f1_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: "../EvolvePro/output/plm/esm/cas12f_esm2_t6_8M_UR50D.csv"
  giacomelli:
    data_loader_type: file_loader
    input_path: "/sc/arion/work/fratac01/data/al/dms/giacomelli_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/giacomelli_esm2_t33_650M_UR50D.csv
  cov2_S:
    data_loader_type: file_loader
    input_path: "/sc/arion/work/fratac01/data/al/dms/cov2_S_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/cov2_S_esm2_t33_650M_UR50D.csv
  doud:
    data_loader_type: file_loader
    input_path: "/sc/arion/work/fratac01/data/al/dms/doud_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/doud_esm2_t33_650M_UR50D.csv
  haddox:
    data_loader_type: file_loader
    input_path: "/sc/arion/work/fratac01/data/al/dms/haddox_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/haddox_esm2_t33_650M_UR50D.csv
  kelsic:
    data_loader_type: file_loader
    input_path: "/sc/arion/work/fratac01/data/al/dms/kelsic_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/kelsic_esm2_t33_650M_UR50D.csv
  lee:
    data_loader_type: file_loader
    input_path: "/sc/arion/work/fratac01/data/al/dms/lee_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/lee_esm2_t33_650M_UR50D.csv
  markin:
    data_loader_type: file_loader
    input_path: "/sc/arion/work/fratac01/data/al/dms/markin_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/markin_esm2_t33_650M_UR50D.csv
  stiffler:
    data_loader_type: file_loader
    input_path: "/sc/arion/work/fratac01/data/al/dms/stiffler_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/stiffler_esm2_t33_650M_UR50D.csv
  zikv_E:
    data_loader_type: file_loader
    input_path: "/sc/arion/work/fratac01/data/al/dms/zikv_E_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/zikv_E_esm2_t33_650M_UR50D.csv
c1:
  data_loader:
    type: file_loader
    dataset_name: "cas12f"
    # input_path: "../../data/al/dms/brenan_labels.csv"
    # input_path: "../../data/al/dms/cas12f1_labels.csv"
    input_path: "../../data/al/dms/cas12f_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      # name_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
  data_loader1:
    input_path: "../../data/al/dms/brenan1_labels.csv"
    # input_path: "./test_data/test_assay_small1.csv"
    column_names:
      id_col: "id"
      # name_col: "id"
      sequence_col: "sequence"
      score_col: "score"
    sequence_generator:
      name: single_aa_substitution
      wt_fasta_file: "./test_data/test_assay_small1.fasta"
      substitution_col: "variant"
  embedder:
    type: file_loader
    model_name: esm2_t2_8M_UR50D
    # embeddings_file: ../../data/al/esm/brenan1_esm2_t6_8M_UR50D.csv
    embeddings_file: ../../data/al/esm/cas12f_esm2_t6_8M_UR50D.csv
  embedder1:
    type: esm
    model_name: esm2_t2_8M_UR50D
    parameters:
      cache_dir: "./model_cache"
      device: "cpu"
      batch_size: 8
      use_pooling: true
      quantize: false
c2:
  data_loader:
    type: file_loader
    dataset_name: "cas12f"
    # input_path: "../../data/al/dms/brenan_labels.csv"
    input_path: "../../data/al/dms/cas12f1_labels.csv"
    # input_path: "../../data/al/dms/cas12f_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      # name_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
  embedder:
    type: file_loader
    model_name: esm2_t2_8M_UR50D
    # embeddings_file: ../../data/al/esm/brenan1_esm2_t6_8M_UR50D.csv
    embeddings_file: ../../data/al/esm/cas12f_esm2_t6_8M_UR50D.csv
c3:
  data_loader:
    type: file_loader
    dataset_name: "cas12f"
    # input_path: "../../data/al/dms/brenan_labels.csv"
    # input_path: "../../data/al/dms/cas12f1_labels.csv"
    input_path: "/sc/arion/work/fratac01/data/al/dms/cas12f_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      # name_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
  embedder:
    type: file_loader
    model_name: esm2_t2_8M_UR50D
    # embeddings_file: ../../data/al/esm/brenan1_esm2_t6_8M_UR50D.csv
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/cas12f_esm2_t6_8M_UR50D.csv
c3_1:
  default_dataset: cas12f
  embedder:
    type: file_loader
    model_name: esm2_t33_650M_UR50D
    # embeddings_file: ../../data/al/esm/brenan1_esm2_t6_8M_UR50D.csv
    # embeddings_file: /sc/arion/work/fratac01/data/al/esm/cas12f_esm2_t33_650M_UR50D.csv
    # embeddings_file: /sc/arion/work/fratac01/data/al/esm/haddox_esm2_t33_650M_UR50D.csv
c4:
  data_loader:
    type: file_loader
    dataset_name: "cas12f"
    # input_path: "../../data/al/dms/brenan_labels.csv"
    # input_path: "../../data/al/dms/cas12f1_labels.csv"
    input_path: "../../data/al/dms/cas12f_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      # name_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
  embedder:
    type: file_loader
    model_name: esm2_t2_8M_UR50D
    # embeddings_file: ../../data/al/esm/brenan1_esm2_t6_8M_UR50D.csv
    embeddings_file: ../../data/al/esm/cas12f_esm2_t6_8M_UR50D.csv
c5:
  data_loader:
    type: file_loader
    dataset_name: "cas12f"
    # input_path: "../../data/al/dms/brenan_labels.csv"
    # input_path: "../../data/al/dms/cas12f1_labels.csv"
    input_path: "../../data/al/dms/cas12f_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      # name_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
  embedder:
    type: file_loader
    model_name: esm2_t2_8M_UR50D
    # embeddings_file: ../../data/al/esm/brenan1_esm2_t6_8M_UR50D.csv
    embeddings_file: ../../data/al/esm/cas12f_esm2_t6_8M_UR50D.csv
c6:
  data_loader:
    type: file_loader
    dataset_name: "cas12f"
    # input_path: "../../data/al/dms/brenan_labels.csv"
    # input_path: "../../data/al/dms/cas12f1_labels.csv"
    input_path: "../../data/al/dms/cas12f_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      # name_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
  embedder:
    type: file_loader
    model_name: esm2_t2_8M_UR50D
    # embeddings_file: ../../data/al/esm/brenan1_esm2_t6_8M_UR50D.csv
    embeddings_file: ../../data/al/esm/cas12f_esm2_t6_8M_UR50D.csv
c7:
  data_loader:
    type: file_loader
    dataset_name: "cas12f"
    # input_path: "../../data/al/dms/brenan_labels.csv"
    # input_path: "../../data/al/dms/cas12f1_labels.csv"
    input_path: "../../data/al/dms/cas12f_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      # name_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
  embedder:
    type: file_loader
    model_name: esm2_t2_8M_UR50D
    # embeddings_file: ../../data/al/esm/brenan1_esm2_t6_8M_UR50D.csv
    embeddings_file: ../../data/al/esm/cas12f_esm2_t6_8M_UR50D.csv
c8:
  data_loader:
    type: file_loader
    dataset_name: "cas12f"
    # input_path: "../../data/al/dms/brenan_labels.csv"
    # input_path: "../../data/al/dms/cas12f1_labels.csv"
    input_path: "../../data/al/dms/cas12f_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      # name_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
  embedder:
    type: file_loader
    model_name: esm2_t2_8M_UR50D
    # embeddings_file: ../../data/al/esm/brenan1_esm2_t6_8M_UR50D.csv
    embeddings_file: ../../data/al/esm/cas12f_esm2_t6_8M_UR50D.csv
c9_1:
  default_dataset: cas12f
  simulation_config_id: c9_1
c9_3:
  default_dataset: cas12f
  simulation_config_id: c9_3
