c1:
  - name: "RF50"
    description: "First simulation"
    learner1:
      type: "RidgeRegression"
      name: "RidgeRegression"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        input_dim: 128
        alpha: 1.0
        num_estimators: 10
    learner:
      type: "RandomForestRegression"
      name: "RF50"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        # input_dim: 128
        n_estimators: 50 #100
        criterion: friedman_mse
        max_depth: null
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: 1.0
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: null
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null
    first_round_acquisition_strategy:
      type: "Random"
      name: "Random"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Random"
        name: "Random"
        parameters: {}
        uses_random_seed: true
      - type: "Greedy"
        name: "Greedy"
        parameters: {}
        uses_random_seed: false
      - type: "UCB"
        name: "UCB"
        parameters:
          exploration_weight: 1.0
        uses_random_seed: false
      - type: "Variance"
        name: "Variance"
        parameters: {}
        uses_random_seed: false
      - type: "ExpectedImprovement"
        name: "EI"
        parameters: {}
        uses_random_seed: false
      - type: "ThompsonSampling"
        name: "TS"
        parameters: {}
        uses_random_seed: true
    acquisition_strategies1:
      - type: "Greedy"
        name: "Greedy"
        parameters: {}
        uses_random_seed: false
c2:
  - name: "C2RF50"
    description: "First simulation"
    learner1:
      type: "RidgeRegression"
      name: "RR"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        input_dim: 128
        alpha: 1.0
        num_estimators: 10
    learner:
      type: "RandomForestRegression"
      name: "RF10"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        # input_dim: 128
        n_estimators: 10 #100
        criterion: friedman_mse
        max_depth: null
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: 1.0
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: null
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rand"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Greedy"
        name: "Greed"
        parameters: {}
        uses_random_seed: false
c3:
  - name: "C3RF508M"
    description: "First simulation"
    learner:
      type: "RandomForestRegression"
      name: "RF100"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        # input_dim: 128
        n_estimators: 100 #100
        criterion: friedman_mse
        max_depth: null
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: 1.0
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: null
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rnd"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Greedy"
        name: "Grd"
        parameters: {}
        uses_random_seed: false
c3_1:
  - name: "C3RF50650M"
    description: "First simulation"
    learner:
      type: "RandomForestRegression"
      name: "RF_AL"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        # input_dim: 128
        n_estimators: 20 #100 #100
        criterion: friedman_mse
        max_depth: null
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: 1.0
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: null
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rnd"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Greedy"
        name: "Grd"
        parameters: {}
        uses_random_seed: false
c3_2:
  - name: "C3RF50650M"
    description: "First simulation"
    learner:
      type: "RandomForestRegression"
      name: "RFTRAIN_ALL"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        # input_dim: 128
        n_estimators: 20 #100 #100
        criterion: friedman_mse
        max_depth: null
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: 1.0
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: null
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rnd"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Greedy"
        name: "Grd"
        parameters: {}
        uses_random_seed: false
c4:
  - name: "RF50"
    description: "First simulation"
    learner:
      type: "RandomForestRegression"
      name: "RF50"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        # input_dim: 128
        n_estimators: 50 #100
        criterion: friedman_mse
        max_depth: null
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: 1.0
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: null
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rnd"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Random"
        name: "Rnd"
        parameters: {}
        uses_random_seed: true
c5:
  - name: "RF50"
    description: "First simulation"
    learner:
      type: "RandomForestRegression"
      name: "RF50"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        # input_dim: 128
        n_estimators: 50 #100
        criterion: friedman_mse
        max_depth: null
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: 1.0
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: null
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rnd"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "UCB"
        name: "UCB"
        parameters:
          exploration_weight: 1.0
        uses_random_seed: false
c6:
  - name: "RF50"
    description: "First simulation"
    learner:
      type: "RandomForestRegression"
      name: "RF50"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        # input_dim: 128
        n_estimators: 50 #100
        criterion: friedman_mse
        max_depth: null
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: 1.0
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: null
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rnd"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Variance"
        name: "Variance"
        parameters: {}
        uses_random_seed: false
c7:
  - name: "RF50"
    description: "First simulation"
    learner:
      type: "RandomForestRegression"
      name: "RF50"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        # input_dim: 128
        n_estimators: 50 #100
        criterion: friedman_mse
        max_depth: null
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: 1.0
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: null
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rnd"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "ExpectedImprovement"
        name: "EI"
        parameters: {}
        uses_random_seed: false
c8:
  - name: "RF50"
    description: "First simulation"
    learner:
      type: "RandomForestRegression"
      name: "RF50"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        # input_dim: 128
        n_estimators: 50 #100
        criterion: friedman_mse
        max_depth: null
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: 1.0
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: null
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rnd"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "ThompsonSampling"
        name: "TS"
        parameters: {}
        uses_random_seed: true
c9:
  - name: "C2RF50"
    description: "First simulation"
    learner:
      type: "ESM2MLPRegression"
      name: "RF10"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        base_model_name: facebook/esm2_t6_8M_UR50D
        # base_model_name: facebook/esm2_t33_650M_UR50D
        use_pooling: true
        batch_size: 4
        num_layers_to_unfreeze: 2
        num_epochs: 2
      parameters1:
        # input_dim: 128
        n_estimators: 10 #100
        criterion: friedman_mse
        max_depth: null
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: 1.0
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: null
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rand"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Greedy"
        name: "Greed"
        parameters: {}
        uses_random_seed: false
c9_1:
  - name: "C2RF50"
    description: "First simulation"
    learner:
      type: "ESM2MLPRegression"
      name: "RF10"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        # base_model_name: facebook/esm2_t6_8M_UR50D
        base_model_name: facebook/esm2_t33_650M_UR50D
        use_pooling: true
        batch_size: 64
        num_layers_to_unfreeze: 6
        num_epochs: 10
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rand"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Greedy"
        name: "Greed"
        parameters: {}
        uses_random_seed: false
c9_2:
  - name: "C2RF50"
    description: "First simulation"
    learner:
      type: "ESM2HingeForestRegression"
      name: "RF10"
      uses_embedder: false
      uses_random_seed: false
      parameters:
        base_model_name: facebook/esm2_t6_8M_UR50D
        # base_model_name: facebook/esm2_t33_650M_UR50D
        use_pooling: true
        batch_size: 4 #64
        num_layers_to_unfreeze: 2 #6
        num_epochs: 2 #10
        num_trees: 10
        tree_depth: 6
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rand"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Greedy"
        name: "Greed"
        parameters: {}
        uses_random_seed: false
c9_3:
  - name: "C2RF50"
    description: "First simulation"
    learner:
      type: "ESM2HingeForestRegression"
      name: "RF10"
      uses_embedder: false
      uses_random_seed: false
      uses_wt_sequence: false
      parameters:
        #base_model_name: facebook/esm2_t6_8M_UR50D
        base_model_name: facebook/esm2_t33_650M_UR50D
        use_pooling: true
        batch_size: 64
        num_layers_to_unfreeze: 6
        num_epochs: 10
        num_trees: 20
        tree_depth: 6
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rand"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Greedy"
        name: "Greed"
        parameters: {}
        uses_random_seed: false
c10:
  - name: "C3RF50650M"
    description: "First simulation"
    learner:
      type: "ESM2LogLikelihood"
      name: "RF100"
      uses_embedder: false
      uses_random_seed: false
      uses_wt_sequence: true
      parameters:
        base_model_name: facebook/esm2_t6_8M_UR50D
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rnd"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Greedy"
        name: "Grd"
        parameters: {}
        uses_random_seed: false
