c1:
  - name: "RF50"
    description: "First simulation"
    learner1:
      type: "RidgeRegression"
      name: "RidgeRegression"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        input_dim: 128
        alpha: 1.0
        num_estimators: 10
    learner:
      type: "RandomForestRegression"
      name: "RF50"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        # input_dim: 128
        n_estimators: 50 #100
        criterion: friedman_mse
        max_depth: null
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: 1.0
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: null
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null
    first_round_acquisition_strategy:
      type: "Random"
      name: "Random"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Random"
        name: "Random"
        parameters: {}
        uses_random_seed: true
      - type: "Greedy"
        name: "Greedy"
        parameters: {}
        uses_random_seed: false
      - type: "UCB"
        name: "UCB"
        parameters:
          exploration_weight: 1.0
        uses_random_seed: false
      - type: "Variance"
        name: "Variance"
        parameters: {}
        uses_random_seed: false
      - type: "ExpectedImprovement"
        name: "EI"
        parameters: {}
        uses_random_seed: false
      - type: "ThompsonSampling"
        name: "TS"
        parameters: {}
        uses_random_seed: true
    acquisition_strategies1:
      - type: "Greedy"
        name: "Greedy"
        parameters: {}
        uses_random_seed: false
c2:
  - name: "C2RF50"
    description: "First simulation"
    learner1:
      type: "RidgeRegression"
      name: "RR"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        input_dim: 128
        alpha: 1.0
        num_estimators: 10
    learner:
      type: "RandomForestRegression"
      name: "RF10"
      uses_embedder: false
      uses_random_seed: true
      parameters:
        # input_dim: 128
        n_estimators: 10 #100
        criterion: friedman_mse
        max_depth: null
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: 1.0
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: null
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null
    first_round_acquisition_strategy:
      type: "Random"
      name: "Rand"
      parameters: {}
      uses_random_seed: true
    acquisition_strategies:
      - type: "Greedy"
        name: "Greed"
        parameters: {}
        uses_random_seed: false
  # - name: "Simulation 2"
  #   description: "Second simulation"
  #   learner:
  #     name: "MLPRegression"
  #     uses_embedder: true
  #     parameters:
  #       input_dim: 128
  #       alpha: 0.0001
  #       hidden_layer_sizes: [64, 32]
  #       learning_rate_init: 0.001
  #       max_iter: 200
  #       num_dropout_samples: 10
  #       random_state: 42
  # - name: "Simulation 2"
  #   description: "Second simulation"
  #   config_path: "./config/simulations/sim2.yaml"
  # - name: "Simulation 3"
  #   description: "Third simulation"
  #   config_path: "./config/simulations/sim3.yaml"
