
  ADRB2:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/ADRB2_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/ADRB2_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/ADRB2.fasta
  AICDA:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/AICDA_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/AICDA_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/AICDA.fasta
  BRCA1:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/BRCA1_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/BRCA1_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/BRCA1.fasta
  BRCA2:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/BRCA2_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/BRCA2_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/BRCA2.fasta
  CALM1:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/CALM1_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/CALM1_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/CALM1.fasta
  CAR11:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/CAR11_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/CAR11_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/CAR11.fasta
  CASP3:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/CASP3_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/CASP3_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/CASP3.fasta
  CASP7:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/CASP7_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/CASP7_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/CASP7.fasta
  CBS:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/CBS_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/CBS_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/CBS.fasta
  GDIA:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/GDIA_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/GDIA_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/GDIA.fasta
  GRB2:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/GRB2_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/GRB2_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/GRB2.fasta
  HEM3:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/HEM3_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/HEM3_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/HEM3.fasta
  HMDH:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/HMDH_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/HMDH_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/HMDH.fasta
  HXK4:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/HXK4_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/HXK4_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/HXK4.fasta
  KCNE1:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/KCNE1_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/KCNE1_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/KCNE1.fasta
  KCNH2:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/KCNH2_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/KCNH2_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/KCNH2.fasta
  MET:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/MET_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/MET_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/MET.fasta
  MK01:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/MK01_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/MK01_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/MK01.fasta
  MSH2:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/MSH2_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/MSH2_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/MSH2.fasta
  MTHR:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/MTHR_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/MTHR_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/MTHR.fasta
  NPC1:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/NPC1_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/NPC1_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/NPC1.fasta
  OTC:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/OTC_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/OTC_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/OTC.fasta
  P53:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/P53_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/P53_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/P53.fasta
  PAI1:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/PAI1_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/PAI1_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/PAI1.fasta
  PPARG:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/PPARG_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/PPARG_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/PPARG.fasta
  PPM1D:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/PPM1D_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/PPM1D_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/PPM1D.fasta
  PTEN:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/PTEN_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/PTEN_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/PTEN.fasta
  RAF1:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/RAF1_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/RAF1_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/RAF1.fasta
  RASH:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/RASH_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/RASH_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/RASH.fasta
  S22A1:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/S22A1_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/S22A1_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/S22A1.fasta
  SC6A4:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/SC6A4_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/SC6A4_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/SC6A4.fasta
  SCN5A:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/SCN5A_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/SCN5A_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/SCN5A.fasta
  SERC:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/SERC_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/SERC_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/SERC.fasta
  SHOC2:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/SHOC2_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/SHOC2_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/SHOC2.fasta
  SRC:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/SRC_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/SRC_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/SRC.fasta
  SUMO1:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/SUMO1_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/SUMO1_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/SUMO1.fasta
  SYUA:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/SYUA_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/SYUA_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/SYUA.fasta
  TADBP:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/TADBP_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/TADBP_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/TADBP.fasta
  TPK1:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/TPK1_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/TPK1_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/TPK1.fasta
  TPOR:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/TPOR_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/TPOR_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/TPOR.fasta
  UBC9:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/UBC9_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/UBC9_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/UBC9.fasta
  VKOR1:
    data_loader_type: file_loader
    input_path: /sc/arion/work/fratac01/data/al/dms/VKOR1_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      sequence_col: "mutant"
      score_col: "DMS_score"
    embeddings_file: /sc/arion/work/fratac01/data/al/esm/VKOR1_esm2_t33_650M_UR50D.csv
    fasta_file: /sc/arion/work/fratac01/data/al/dms/VKOR1.fasta